{% set name = "incremental" %}
{% set version = "24.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3717c20534499835555ba727b32ee087945ba9daaf23851471dfe3d1e3d1698

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
  run:
    - python >=3.8
    - setuptools >=61.0

test:
  imports:
    - incremental
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/twisted/incremental
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Incremental is a small library that versions your Python projects.
  dev_url: https://github.com/twisted/incremental

extra:
  recipe-maintainers:
    - isuruf
    - synapticarbors
