{% set name = "incremental" %}
{% set version = "24.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb4f1d47ee60efe87d4f6f0ebb5f70b9760db2b2574c59c8e8912be4ebd464c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
  run:
    - python >=3.8
    - setuptools >=61.0

test:
  imports:
    - incremental
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/twisted/incremental
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Incremental is a small library that versions your Python projects.
  dev_url: https://github.com/twisted/incremental

extra:
  recipe-maintainers:
    - isuruf
    - synapticarbors
